INV_MVC/Controllers/CatalogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Entidades;
using System.IO;
using Microsoft.Reporting.WebForms;

namespace INV_MVC.Controllers
{
    [Authorize]
    public class CatalogosController : baseController
    {
        private EstadoUsuariosLogic EstadoUsuariosLogic = new EstadoUsuariosLogic();
        private CategoriaLogic categoriaLogic = new CategoriaLogic();
        private UnidadesLogic unidadesLogic = new UnidadesLogic();
        private MonedasLogic monedasLogic = new MonedasLogic();
        private ProductoLogic productoLogic = new ProductoLogic();
        private ProductoImagesLogic productoImagesLogic = new ProductoImagesLogic();

        // GET: Catalogos
        public ActionResult Index()
        {
            return View();
        }
        #region Metodos EstadoUsuarios
        public ActionResult EstadosUsuariosListar()
        {
            ViewBag.breadcrumb = "Catalogos/Estados Usuarios";
            ViewBag.pageheader = "Estado de Usuarios";
            ViewBag.Heading = "Lista de Estados Usuarios";
            var lista = EstadoUsuariosLogic.GetAllEstadosUsuarios();
            return PartialView("_EstadosUsuariosListar", lista);
        }
        public ActionResult EstadosUsuariosAdd()
        {
            ViewBag.ModalHeading = "Agregar Estado Usuario";
            EstadoUsuarios model = new EstadoUsuarios();
            return PartialView("_EstadosUsuariosAddUpd", model);
        }

        public ActionResult EstadosUsuariosEdit(int id)
        {
            ViewBag.ModalHeading = "Editar Estado Usuario";
            EstadoUsuarios model = EstadoUsuariosLogic.GetEstadosUsuariosById(id);
            return PartialView("_EstadosUsuariosAddUpd", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult GuardarEstadosUsuarios(EstadoUsuarios model)
        {
            if (!ModelState.IsValid)
                return PartialView("_EstadosUsuariosAddUpd", model);
            var respuesta = EstadoUsuariosLogic.Guardar(model);
            if (!respuesta.response)
            {
                ModelState.AddModelError("", respuesta.mensaje);
                return PartialView("_EstadosUsuariosAddUpd", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("EstadosUsuariosListar");
            return Json(respuesta);

        }
        public ActionResult EstadosUsuariosEliminar(int id)
        {
            ViewBag.ModalHeading = "Eliminar Estado Usuario";
            EstadoUsuarios model = EstadoUsuariosLogic.GetEstadosUsuariosById(id);
            return PartialView("_EstadosUsuariosEliminar", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EstadosUsuariosEliminarById(int id)
        {
            ViewBag.ModalHeading = "Eliminar Estado Usuario";
            if (!ModelState.IsValid)
            {
                EstadoUsuarios model = EstadoUsuariosLogic.GetEstadosUsuariosById(id);
                return PartialView("_EstadosUsuariosEliminar", model);

            }
            var respuesta = EstadoUsuariosLogic.Eliminar(id);
            if (!respuesta.response)
            {
                EstadoUsuarios model = EstadoUsuariosLogic.GetEstadosUsuariosById(id);
                return PartialView("_EstadosUsuariosEliminar", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("EstadosUsuariosListar");
            return Json(respuesta);
        }
        public ActionResult ReturJson(int id)
        {
            var respuesta = new RespondModel();
            respuesta.href = Url.Action("EstadosUsuariosListar");
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region MetodosCategoría

        public ActionResult CategoriasListar()
        {
            ViewBag.breadcrumb = "Catalogos/Categorías de Productos";
            ViewBag.pageheader = "Categorías de Productos";
            ViewBag.Heading = "Lista de Categorías";
            var lista = categoriaLogic.GetAll();
            return PartialView("_CategoriasListar", lista);
        }

        public ActionResult CategoriaAdd()
        {
            ViewBag.ModalHeading = "Agregar Categoría de Productos";
            ViewBag.Categorias = new SelectList(categoriaLogic.GetAll(), "Id", "Nombre");
            Categoria model = new Categoria();
            return PartialView("_CategoriasAddUpd", model);
        }

        public ActionResult CategoriaEdit(int id)
        {
            ViewBag.ModalHeading = "Editar Categoría de Productos";
            ViewBag.Categorias = new SelectList(categoriaLogic.GetAll(), "Id", "Nombre");
            Categoria model = categoriaLogic.GetCategoríaPorId(id);
            return PartialView("_CategoriasAddUpd", model);
        }

        public ActionResult CategoriaEliminar(int id)
        {
            ViewBag.ModalHeading = "Eliminar Categoría";
            Categoria model = categoriaLogic.GetCategoríaPorId(id);
            return PartialView("_CategoriaEliminar", model);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]

        public ActionResult GuardarCategoria(Categoria model)
        {
            ViewBag.ModalHeading = model.Id == 0 ? "Agregar Categoría de Producto" : "Editar Categoría de Productos";
            ViewBag.Categorias = new SelectList(categoriaLogic.GetAll(), "Id", "Nombre");
            model.UsuarioCrea = Usuario.UserId;
            model.FechaCreacion = DateTime.Now;
            //model.CategoriaParentId = model.CategoriaParentId ?? 0;
            if (!ModelState.IsValid)
                return PartialView("_CategoriasAddUpd", model);
            var respuesta = categoriaLogic.Guardar(model);
            if (!respuesta.response)
            {
                ModelState.AddModelError("", respuesta.mensaje);
                return PartialView("_CategoriasAddUpd", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("CategoriasListar");
            return Json(respuesta);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CategoriaEliminarById(int id)
        {
            ViewBag.ModalHeading = "Eliminar Categoría de Productos";
            if (!ModelState.IsValid)
            {
                Categoria model = categoriaLogic.GetCategoríaPorId(id);
                return PartialView("_CategoriaEliminar", model);

            }
            var respuesta = categoriaLogic.Eliminar(id);
            if (!respuesta.response)
            {
                Categoria model = categoriaLogic.GetCategoríaPorId(id);
                return PartialView("_CategoriaEliminar", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("CategoriasListar");
            return Json(respuesta);
        }

        [HttpGet]
        //public JsonResult ConsultaProductos()
        //{
        //    //WsConsulta.wsSoapClient db = new WsConsulta.wsSoapClient();
        //    //var wsconsulta = db.GetProductos().ToList();
        //    //return Json(wsconsulta, JsonRequestBehavior.AllowGet);
        //}

        //public ActionResult ProductosAll()
        //{
        //    var rs = from t in ListarProductos.ObtenerProductos()
        //             select t;
        //    return View(rs.ToList());
        //}

        public ActionResult ProductosAll()
        {
            ViewBag.breadcrumb = "Catalogos/Lista de Productos";
            ViewBag.pageheader = "Lista de Productos";
            ViewBag.Heading = "Lista de Productos";
            var rs = from t in ListarProductos.ObtenerProductos()
                     select t;
            return PartialView("_ProductosAll", rs);
        }



        #endregion

        #region MetodosUnidades

        public ActionResult UnidadesListar()
        {
            ViewBag.breadcrumb = "Catalogos/Unidades";
            ViewBag.pageheader = "Lista de Unidades";
            ViewBag.Heading = "Lista de Unidades de Productos";
            var lista = unidadesLogic.GetAll();
            return PartialView("_UnidadesListar", lista);
        }

        public ActionResult UnidadAdd()
        {
            ViewBag.ModalHeading = "Agregar Unidades de Productos";
            //ViewBag.Unidades = new SelectList(unidadesLogic.GetAll(), "Id", "Nombre");
            Unidades model = new Unidades();
            return PartialView("_UnidadesAddUpd", model);
        }

        public ActionResult UnidadEdit(int id)
        {
            ViewBag.ModalHeading = "Editar Unidades de Productos";

            Unidades model = unidadesLogic.GetUnidadesPorId(id);
            return PartialView("_UnidadesAddUpd", model);
        }

        public ActionResult UnidadEliminar(int id)
        {
            ViewBag.ModalHeading = "Eliminar Unidad";
            Unidades model = unidadesLogic.GetUnidadesPorId(id);
            return PartialView("_UnidadEliminar", model);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]

        public ActionResult GuardarUnidad(Unidades model)
        {
            ViewBag.ModalHeading = model.Id == 0 ? "Agregar Unidades de Producto" : "Editar Unidades de Productos";

            model.UsuarioCrea = Usuario.UserId;
            model.FechaCreacion = DateTime.Now;

            if (!ModelState.IsValid)
                return PartialView("_UnidadesAddUpd", model);
            var respuesta = unidadesLogic.Guardar(model);
            if (!respuesta.response)
            {

INV_MVC/Views/Catalogos/EstadosUsuariosListar.cshtml
@model IEnumerable<Entidades.EstadoUsuarios>
<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">@ViewBag.breadcrumb</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">@ViewBag.pageheader</h4>
    </div>
</div><!--/.row-->
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DesEstadoUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DesEstadoUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

INV_MVC/Views/Catalogos/_CategoriaEliminar.cshtml
@model Entidades.Categoria

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>
@using (Html.BeginForm("CategoriaEliminarById", "Catalogos", new { id = Model.Id }, FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <p>Esta Seguro de Eliminar la categoría: <span class="bg-danger">@Model.Nombre</span> Descripción: <span class="bg-danger">@Model.DesCategoria</span> </p>

    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Catalogos/_CategoriasAddUpd.cshtml
@model Entidades.Categoria

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>




@using (Html.BeginForm("GuardarCategoria", "Catalogos", FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-horizontal">
            @*<h4>EstadoUsuarios</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CategoriaParentId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownList("CategoriaParentId", (SelectList)ViewBag.Categorias, "Seleccionar Categoría", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoriaParentId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DesCategoria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DesCategoria, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DesCategoria, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Catalogos/_CategoriasListar.cshtml
@model IEnumerable<Entidades.Categoria>
<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">@ViewBag.breadcrumb</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">@ViewBag.pageheader</h4>
    </div>
</div><!--/.row-->
<div class="panel panel-default">
    <div class="panel-heading">
        @ViewBag.Heading
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                
                <div class="btn-group" role="group" aria-label="...">
                    @Html.ActionLink("Agregar", "CategoriaAdd", "Catalogos", null, new { @class = "btn btn-primary", data_modal = "" })
                    

                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Exportar
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Excel", "ReporteCategoria", "Catalogos", new { FileType = "Excel", ContentType = "application/vnd.ms-excel" }, null)</li>
                            <li>@Html.ActionLink("Pdf", "ReporteCategoria", "Catalogos", new { FileType = "PDF", ContentType = "application/pdf" }, null)</li>
                            @*<li><a href="#">Dropdown link</a></li>
                <li><a href="#">Dropdown link</a></li>*@
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <table class="table-bordered table-condensed">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)

                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DesCategoria)
                    </th>
                    <th>
                        Categoría Padre
                    </th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DesCategoria)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PadreCategoria.Nombre)
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Editar", "CategoriaEdit", new { id = item.Id }, new { data_modal = "" })</li>
                                    <li>@Html.ActionLink("Eliminar", "CategoriaEliminar", new { id = item.Id }, new { data_modal = "" })</li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

<script src="~/Scripts/app/modalform.js"></script>

INV_MVC/Views/Catalogos/_EstadosUsuariosAddUpd.cshtml
@model Entidades.EstadoUsuarios
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>




@using (Html.BeginForm("GuardarEstadosUsuarios", "Catalogos", FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-horizontal">
            @*<h4>EstadoUsuarios</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.DesEstadoUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DesEstadoUsuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DesEstadoUsuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}


@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

INV_MVC/Views/Catalogos/_EstadosUsuariosListar.cshtml
@model IEnumerable<Entidades.EstadoUsuarios>
<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">@ViewBag.breadcrumb</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">@ViewBag.pageheader</h4>
    </div>
</div><!--/.row-->
<div class="panel panel-default">
    <div class="panel-heading">
        @ViewBag.Heading
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="btn-group" role="group" aria-label="...">
                    @Html.ActionLink("Agregar", "EstadosUsuariosAdd", "Catalogos", null, new { @class = "btn btn-primary", data_modal = "" })
                    @*<button type="button" class="btn btn-default">1</button>
                    <button type="button" class="btn btn-default">2</button>*@

                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Exportar
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Excel", "ReporteEstadoUsuarios", "Catalogos", new { FileType = "Excel", ContentType = "application/vnd.ms-excel" },null)</li>
                            <li>@Html.ActionLink("Pdf", "ReporteEstadoUsuarios", "Catalogos", new { FileType = "PDF", ContentType = "application/pdf" },null)</li>
                            @*<li><a href="#">Dropdown link</a></li>
                            <li><a href="#">Dropdown link</a></li>*@
                        </ul>
                    </div>
                </div>
                
            </div>
        </div>
        <table class="table-bordered table-condensed">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.DesEstadoUsuario)

                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Codigo)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DesEstadoUsuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Codigo)
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Editar", "EstadosUsuariosEdit", new { id = item.Id }, new { data_modal = "" })</li>
                                    <li>@Html.ActionLink("Eliminar", "EstadosUsuariosEliminar", new { id = item.Id }, new { data_modal = "" })</li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

<script src="~/Scripts/app/modalform.js"></script>

INV_MVC/Views/Catalogos/_MonedaEliminar.cshtml
@model Entidades.Monedas
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>
@using (Html.BeginForm("MonedaEliminarById", "Catalogos", new { id = Model.Id }, FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <p>Esta Seguro de Eliminar la moneda: <span class="bg-danger">@Model.Nombre</span> Codigo: <span class="bg-danger">@Model.Simbolo</span> </p>

    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Catalogos/_ProductoImageAddUpd.cshtml
@model Entidades.ProductoImages
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>

@using (Html.BeginForm("GuardarProductoImages", "Catalogos", FormMethod.Post, new { id = "form-01", role = "form",  enctype = "multipart/form-data" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IdProducto)
        <div class="form-horizontal">
            @*<h4>EstadoUsuarios</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="productoimage" id="productoimage" accept=".png,.jpg,.jpeg" />
                </div>
            </div>


        </div>
    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Catalogos/_UnidadEliminar.cshtml
@model Entidades.Unidades

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>
@using (Html.BeginForm("UnidadEliminarById", "Catalogos", new { id = Model.Id }, FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <p>Esta Seguro de Eliminar la categoría: <span class="bg-danger">@Model.DesUnidades</span> Descripción: <span class="bg-danger">@Model.Codigo</span> </p>

    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}