INV_MVC/Models/CuentaViewModel/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace INV_MVC.Models.CuentaViewModel
{
    public class LoginViewModel
    {
        [Display(Name = "Email o Usuario")]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Display(Name ="Password")]
        public string Password { get; set; }

    }
}

INV_MVC/Controllers/CuentaController.cs
using Entidades;
using INV_MVC.Helpers;
using INV_MVC.Models;
using INV_MVC.Models.CuentaViewModel;
using INV_MVC.Models.Seguridad;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Negocio;
using Newtonsoft.Json;
using reCAPTCHA.MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace INV_MVC.Controllers
{
    [Authorize]
    public class CuentaController : baseController
    {
        private UsuariosLogic userlogic = new UsuariosLogic();
        private PerfilSeguridadLogic perfilseg = new PerfilSeguridadLogic();
        private Utilidades util = new Utilidades();
        private RolesLogic RolesLogic = new RolesLogic();
        private RolesAccionesLogic rolesAccionesLogic = new RolesAccionesLogic();
        private AccionesLogic accionesLogic = new AccionesLogic();
        // GET: Cuenta
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var responloging = userlogic.LogIng(model.Email, model.Password, util.GetKey, util.GetIV);
            if (responloging.response)
            {
                var Usuario = userlogic.GetUsuariosPorUserName(model.Email);
                UsuarioViewModel user = new UsuarioViewModel
                {
                    UserName = Usuario.UserName,
                    Email = Usuario.Email,
                    UserId = Usuario.Id
                };
                SignIn(user);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", responloging.mensaje);
            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Registrarse()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        [CaptchaValidator]
        public ActionResult Registrarse(RegistroUsuarioViewModel model, bool captchaValid)
        {
            if (!ModelState.IsValid)
            {
                if (!captchaValid)
                    ModelState.AddModelError("", "Favor validar que no eres un robot.");
                return View(model);
            }
                
            try
            {
                var perfil = perfilseg.GetPerfilbyId(1);

                var ValidPassword = CheckPassword(model.Password, perfil.LenMinPass, perfil.CantLetrasMin, perfil.CantLetrasMayMin, perfil.CantNumeroMin, perfil.CantCharEspecialMin);

                if (!ValidPassword.IsValid) {
                    foreach (var item in ValidPassword.Mensajes)
                    {
                        ModelState.AddModelError("", item);
                    }
                    return View(model);
                }

                var respuesta = userlogic.RegistrarUsuario(new Entidades.Usuarios { Email = model.Email, Password = util.encriptar(model.Password) });
                if (respuesta.response)
                    return RedirectToAction("Login");
                ModelState.AddModelError("", respuesta.mensaje);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }
        public ActionResult UserState() {
            var model = Usuario;
            return PartialView("_UserState", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Logoff()
        {
            Signout();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult RolesListar() {
            ViewBag.breadcrumb = "Cuenta/Seguridad";
            ViewBag.pageheader = "Seguridad";
            ViewBag.Heading = "Roles y permisos";

            var model = RolesLogic.GetAll();
            return PartialView("_RolesListar",model);

        }
        public ActionResult RolesAdd()
        {
            ViewBag.ModalHeading = "Agregar Rol";
            Roles model = new Roles();
            return PartialView("_RolesAddUpd", model);
        }

        public ActionResult RolesEdit(int id)
        {
            ViewBag.ModalHeading = "Editar Rol";
            Roles model = RolesLogic.GetRolesPorId(id);
            return PartialView("_RolesAddUpd", model);
        }
        public ActionResult RolPermisos(int id) {
            var rol = RolesLogic.GetRolesPorId(id);
            var acciones = accionesLogic.GetAll();
            RolAddPermisoViewModel model = new RolAddPermisoViewModel();
            model.Id = rol.Id;
            model.Nombre = rol.Nombre;

            foreach (var item in acciones)
            {
                var exist = rolesAccionesLogic.GetRolesAccionesExist(model.Id, item.Id);
                model.Acciones.Add(new SelectedRolesAccionesEditorViewModel { Accion = item.Accion, Controlador = item.Controlador, IdAccion = item.Id, Selected= exist });
            }

            return PartialView("_RolPermisos", model);
            

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RolPermisos(RolAddPermisoViewModel model)
        {
            foreach (var item in model.Acciones)
            {

                if (item.Selected) {
                    rolesAccionesLogic.Guardar(new RolesAcciones { IdRol = model.Id, IdAcciones = item.IdAccion });
                }
                else {
                    rolesAccionesLogic.Eliminar(model.Id, item.IdAccion);
                }
                
            }

            return PartialView("_RolPermisos", model);


        }

        public ActionResult GuardarRol(Roles model)
        {
            ViewBag.ModalHeading = model.Id == 0 ? "Agregar Rol" : "Editar Rol";

            if (!ModelState.IsValid)
                return PartialView("_RolesAddUpd", model);
            var respuesta = RolesLogic.Guardar(model);
            if (!respuesta.response)
            {
                ModelState.AddModelError("", respuesta.mensaje);
                return PartialView("_RolesAddUpd", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("RolesListar");
            return Json(respuesta);
        }


        #region Autenticacion
        public void SignIn(UsuarioViewModel User, string providerKey = null, bool isPersistent = false)
        {
            var claims = new List<Claim>();

            // create required claims
            claims.Add(new Claim(ClaimTypes.NameIdentifier, User.UserId.ToString()));
            claims.Add(new Claim(ClaimTypes.Name, User.UserName));

            var jsonUserMonitoreo = JsonConvert.SerializeObject(User);

            // custom – my serialized AppUserState object
            claims.Add(new Claim("UsuarioApp", jsonUserMonitoreo));

            var identity = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);

            AuthenticationManager.SignIn(new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = isPersistent,
                ExpiresUtc = DateTime.UtcNow.AddDays(7)
            }, identity);
        }


        public void Signout()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie,
                                            DefaultAuthenticationTypes.ExternalCookie);
        }

        private IAuthenticationManager AuthenticationManager
        {
            //return HttpContext.Current.GetOwinContext().Authentication;
            get { return HttpContext.GetOwinContext().Authentication; }
        }
        #endregion
        #region MetodosApoyo
        public ValidationClass CheckPassword(string pass, int LenMinPass, int CantLetrasMin, int CantLetrasMayMin, int CantNumeroMin, int CantCharEspecialMin)
        {
            ValidationClass validaciones = new ValidationClass();
            bool respond = true;
            //respondModel.SetResponse(true, "Contraseña OK.");
            int contCantLetrasMin = 0;
            int contCantLetrasMayMin = 0;
            int contCantNumeroMin = 0;
            int contCantCharEspecialMin = 0;
            if (pass.Length < LenMinPass)
            {
                validaciones.Mensajes.Add(string.Format("La contraseña debe tener un minimo de {0} caracteres", LenMinPass));
                respond = false;
            }
            /*Validación cantidad de letras*/
            foreach (char c in pass)
            {
                if (char.IsLetter(c))
                    contCantLetrasMin++;

            }
            if (contCantLetrasMin < CantLetrasMin)
            {

                validaciones.Mensajes.Add(string.Format("La contraseña debe tener un minimo de {0} letras", CantLetrasMin));
                respond = false;
            }
            /*Validación cantidad de letras*/

            /*Validación cantidad de letras Mayusculas*/
            foreach (char c in pass)
            {
                if (char.IsUpper(c))
                    contCantLetrasMayMin++;

            }
            if (contCantLetrasMayMin < CantLetrasMayMin)
            {

                validaciones.Mensajes.Add(string.Format("La contraseña debe tener un minimo de {0} mayusculas", CantLetrasMayMin));
                respond = false;
            }
            /*Validación cantidad de letras Mayusculas*/

            /*Validación cantidad de numeros*/
            foreach (char c in pass)
            {
                if (char.IsNumber(c))

INV_MVC/Views/Cuenta/Login.cshtml
@model INV_MVC.Models.CuentaViewModel.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutSinglePage.cshtml";
}

<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">Log in</div>
        <div class="panel-body">
            @using (Html.BeginForm("Login", "Cuenta", FormMethod.Post, new { id = "form-01", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <fieldset>
                <div class="form-group">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "E-mail", name = "Email", type = "email", autofocus = "" })
                </div>
                <div class="form-group">
                    @Html.TextBoxFor(model => model.Password, new { @class = "form-control", placeholder = "Password", name = "Password", type = "password", value = "" })
                </div>
                @*<div class="checkbox">
            <label>
                <input name="remember" type="checkbox" value="Remember Me">Remember Me
            </label>
        </div>*@
                <p class="text-center">
                    <button title="Ingresar" type="submit" class="btn btn-primary">Ingresar</button>
                    </p>
                <p class="text-center">
                    @Html.ActionLink("Registrar", "Registrarse")
                </p>
            </fieldset>
}
        </div>
    </div>
</div><!-- /.col-->

INV_MVC/Views/Cuenta/Registrarse.cshtml
@using reCAPTCHA.MVC
@model INV_MVC.Models.CuentaViewModel.RegistroUsuarioViewModel

@*@{
        /**/

        ViewBag.Title = "Registrarse";
    }*@
@{
    ViewBag.Title = "Registrase";
    Layout = "~/Views/Shared/_LayoutSinglePage.cshtml";
}

<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">@ViewBag.Title</div>
        <div class="panel-body">
            
            @using (Html.BeginForm())
            {
               
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CofirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CofirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CofirmPassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @*@Html.Recaptcha()*@
                            @Html.Recaptcha(publicKey: "6LdwLmgUAAAAAJ5uW24QtYtg0O1N5auxOaLFOv5y", theme: CaptchaTheme.Dark,type:CaptchaType.Image,
            callback: "verifyCallback",expiredCallback:"expiredCallback")
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @*<input type="submit" value="Registrarse" class="btn btn-default" />*@
                            @*<input id="btnAceptar" type="button" class="btn btn-default" value="Aceptar">*@
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div><!-- /.col-->
@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $(document).ready(function () {
        $('#btnAceptar').click(function (e) {
            e.preventDefault();
            var heading = "¿Confirmación?";
            var question = "¿Esta seguro de cambiar la contraseña?";
            var cancelButtonTxt = "Cancelar";
            var okButtonTxt = "Ok";
            var callback = function () {
                $('form').submit();
            }


            confirm(heading, question, cancelButtonTxt, okButtonTxt, callback);
        });
        
    });
    var verifyCallback = function (response) {
        //alert("grecaptcha is ready!");
        $('form').submit();
    };

    var expiredCallback = function () {
        alert("grecaptcha is expired!");
    };
</script>
    
}

INV_MVC/Views/Cuenta/_RolPermisos.cshtml
@model INV_MVC.Models.Seguridad.RolAddPermisoViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>




@using (Html.BeginForm("RolPermisos", "Cuenta", FormMethod.Post, new { id = "form-01" }))
{
<div class="modal-body">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <table class="table table-bordered table-condensed">
        <thead>
            <tr>
                <th>Seleccionado</th>
                <th>Accion</th>
                <th>Controlador</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Acciones != null && Model.Acciones.Count > 0)
            {
                @Html.EditorFor(model=> model.Acciones)
            }
        </tbody>
    </table>
</div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Cuenta/_RolesAddUpd.cshtml
@model Entidades.Roles
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>




@using (Html.BeginForm("GuardarRol", "Cuenta", FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-horizontal">
            @*<h4>EstadoUsuarios</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            

        </div>
    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Cuenta/_RolesListar.cshtml
@model IEnumerable<Entidades.Roles>
<div class="row">
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <em class="fa fa-home"></em>
            </a>
        </li>
        <li class="active">@ViewBag.breadcrumb</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">@ViewBag.pageheader</h4>
    </div>
</div><!--/.row-->
<div class="panel panel-default">
    <div class="panel-heading">
        @ViewBag.Heading
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                @Html.ActionLink("Agregar", "RolesAdd", "Cuenta", null, new { @class = "btn btn-primary", data_modal = "" })
            </div>
        </div>
        <table class="table-bordered table-condensed">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)

                    </th>

                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Editar", "RolesEdit", new { id = item.Id }, new { data_modal = "" })</li>
                                    <li>@Html.ActionLink("Permisos", "RolPermisos", new { id = item.Id }, new { data_modal = "" })</li>
                                    
                                </ul>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

<script src="~/Scripts/app/modalform.js"></script>