INV_MVC/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Entidades;

namespace INV_MVC.Controllers
{
    [Authorize]
    public class ClienteController : baseController
    {
        private ClienteLogic clientelogic = new ClienteLogic();
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ClienteListar()
        {
            ViewBag.Heading = "Lista de Clientes";
            var Listado = clientelogic.GetAll();
            return PartialView("_ClienteListar", Listado);
        }

        public ActionResult ClienteAdd()
        {
            ViewBag.ModalHeading = "Agregar Cliente";
            Cliente model = new Cliente();
            return PartialView("_ClienteAddUpd", model);
        }

        public ActionResult ClienteEdit(int id)
        {
            ViewBag.ModalHeading = "Editar Cliente";
            Cliente model = clientelogic.GetClientePorId(id);
            return PartialView("_ClienteAddUpd", model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]

        public ActionResult GuardarCliente(Cliente model)
        {
            ViewBag.ModalHeading = model.IdCliente == 0 ? "Agregar Cliente" : "Editar Cliente";
            //model.UsuarioCrea = Usuario.UserId;
            //model.FechaCreacion = DateTime.Now;
            //model.CategoriaParentId = model.CategoriaParentId ?? 0;
            if (!ModelState.IsValid)
                return PartialView("_ClienteAddUpd", model);
            var respuesta = clientelogic.Guardar(model);
            if (!respuesta.response)
            {
                ModelState.AddModelError("", respuesta.mensaje);
                return PartialView("_ClienteAddUpd", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("ClienteListar");
            return Json(respuesta);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ClienteEliminarById(int id)
        {
            ViewBag.ModalHeading = "Eliminar Cliente";
            if (!ModelState.IsValid)
            {
                Cliente model = clientelogic.GetClientePorId(id);
                return PartialView("_ClienteEliminar", model);

            }
            var respuesta = clientelogic.Eliminar(id);
            if (!respuesta.response)
            {
                Cliente model = clientelogic.GetClientePorId(id);
                return PartialView("_ClienteEliminar", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("ClienteListar");
            return Json(respuesta);
        }

        public ActionResult ClienteEliminar(int id)
        {
            ViewBag.ModalHeading = "Eliminar Categoría";
            Cliente model = clientelogic.GetClientePorId(id);
            return PartialView("_ClienteEliminar", model);
        }
    }
}

INV_MVC/Views/Cliente/_ClienteAddUpd.cshtml
@model Entidades.Cliente

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>




@using (Html.BeginForm("GuardarCliente", "Cliente", FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdCliente)
        <div class="form-horizontal">
            @*<h4>EstadoUsuarios</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", data_mask = "(+999)-9999-9999" })
                    @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Identificaion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Identificaion, new { @class = "form-control", data_mask = "999-999999-9999a" })
                    @Html.ValidationMessageFor(model => model.Identificaion, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Cliente/_ClienteEliminar.cshtml
@model Entidades.Cliente

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>
@using (Html.BeginForm("ClienteEliminarById", "Cliente", new { id = Model.IdCliente }, FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdCliente)
        <p>Esta Seguro de Eliminar Cliente: <span class="bg-danger">@Model.Nombre</span></p>

    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/Cliente/_ClienteListar.cshtml
@model IEnumerable<Entidades.Cliente>

<div class="panel panel-default">
    <div class="panel-heading">
        @ViewBag.Heading
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                @Html.ActionLink("Agregar", "ClienteAdd", "Cliente", null, new { @class = "btn btn-primary", data_modal = "" })
            </div>
        </div>
        <table id="grid" class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdCliente)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Apellido)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Direccion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Telefono)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.email)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Identificaion)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdCliente)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Direccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Identificaion)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Editar", "CategoriaEdit", new { id = item.IdCliente }, new { data_modal = "" })</li>
                                <li>@Html.ActionLink("Eliminar", "CategoriaEliminar", new { id = item.IdCliente }, new { data_modal = "" })</li>
                            </ul>
                        </div>
                </tr>
        }
            </tbody>

        </table>

    </div>
</div>

<script src="~/Scripts/app/modalform.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#grid').DataTable({
            "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
            //"pageLength": 200
        });
    });
</script>