INV_MVC/Controllers/TasaCambiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;

namespace INV_MVC.Controllers
{
    [Authorize]
    public class TasaCambiosController : baseController
    {
        private TasaCambiosLogic TasaLogic = new TasaCambiosLogic();
        private MonedasLogic monedas = new MonedasLogic();
        private Monedas moneda = new Monedas();
        // GET: TasaCambios
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TasaCambiosListar()
        {
            ViewBag.Heading = "Tasa de Cambios";
            var lista = TasaLogic.GetAll();
            return PartialView("_TasaCambiosListar", lista);
        }

        public ActionResult TasaCambiosAdd()
        {
            ViewBag.ModalHeading = "Agregar Tasa de Cambio";
            ViewBag.TasaCambios = new SelectList(monedas.GetAllMonedas(), "Id", "Nombre");
            TasaCambios model = new TasaCambios();
            return PartialView("_TasaCambiosAddUpd", model);
        }

        public ActionResult TasaCambiosEdit(int id)
        {
            ViewBag.ModalHeading = "Editar Tasa de Cambio";
            ViewBag.TasaCambios = new SelectList(monedas.GetAllMonedas(), "Id", "Nombre");
            TasaCambios model = TasaLogic.GetTasaCambiosPorId(id);
            return PartialView("_TasaCambiosAddUpd", model);
        }

        public ActionResult TasaCambiosEliminar(int id)
        {
            ViewBag.ModalHeading = "Eliminar Tasa de Cambio";
            TasaCambios model = TasaLogic.GetTasaCambiosPorId(id);
            return PartialView("_TasaCambiosEliminar", model);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]

        public ActionResult GuardarTasaCambios(TasaCambios model)
        {
            ViewBag.ModalHeading = model.IdTasaCambio == 0 ? "Agregar Tasa de Cambio" : "Editar Tasa de Cambio";
            ViewBag.TasaCambios = new SelectList(monedas.GetAllMonedas(), "Id", "Nombre");
            model.IdUsuarioReg = Usuario.UserId;
            model.FechaReg = DateTime.Now;
            model.IdUsuarioUpd = Usuario.UserId;
            model.FechaUpd = DateTime.Now;

            if (!ModelState.IsValid)
                return PartialView("_TasaCambiosAddUpd", model);
            var respuesta = TasaLogic.Guardar(model);
            if (!respuesta.response)
            {
                ModelState.AddModelError("", respuesta.mensaje);
                return PartialView("_TasaCambiosAddUpd", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("TasaCambiosListar");
            return Json(respuesta);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TasaCambiosEliminarById(int id)
        {
            ViewBag.ModalHeading = "Eliminar Categoría de Productos";
            if (!ModelState.IsValid)
            {
                TasaCambios model = TasaLogic.GetTasaCambiosPorId(id);
                return PartialView("_TasaCambiosEliminar", model);

            }
            var respuesta = TasaLogic.Eliminar(id);
            if (!respuesta.response)
            {
                TasaCambios model = TasaLogic.GetTasaCambiosPorId(id);
                return PartialView("_TasaCambiosEliminar", model);
            }
            respuesta.IsPartial = true;
            respuesta.ContainerRenderPartial = "renderpartial";
            respuesta.href = Url.Action("TasaCambiosListar");
            return Json(respuesta);
        }
    }
}

INV_MVC/Views/TasaCambios/_TasaCambiosAddUpd.cshtml
@model Entidades.TasaCambios

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>




@using (Html.BeginForm("GuardarTasaCambios", "TasaCambios", FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdTasaCambio)
        <div class="form-horizontal">
            @*<h4>EstadoUsuarios</h4>*@
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IdMonedaLocal, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownList("IdMonedaLocal", (SelectList)ViewBag.TasaCambios, "Seleccionar Moneda", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdMonedaLocal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IdMonedaExtranjera, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @*@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.DropDownList("IdMonedaExtranjera", (SelectList)ViewBag.TasaCambios, "Seleccionar Moneda", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdMonedaExtranjera, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TCoficial, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.TCoficial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TCoficial, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TCventa, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.TCventa, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TCventa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TCcompra, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.TCcompra, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TCcompra, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/TasaCambios/_TasaCambiosEliminar.cshtml
@model Entidades.TasaCambios

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;@ViewBag.ModalHeading</h4>
</div>
@using (Html.BeginForm("TasaCambiosEliminarById", "TasaCambios", new { id = Model.IdTasaCambio }, FormMethod.Post, new { id = "form-01" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IdTasaCambio)
        <p>Esta Seguro de Eliminar la tasa de cambio del dia: <span class="bg-danger">@Model.Fecha</span></p>

    </div>
    <div class="modal-footer">
        <div class="text-center">

            @*<button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>*@
            <button class="btn" data-dismiss="modal"><i class="fa fa-close fa-fw" aria-hidden="true"></i>&nbsp; Cerrar</button>
            <button class="btn btn-primary" type="submit"><i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>&nbsp; Guardar</button>

        </div>
    </div>
}

INV_MVC/Views/TasaCambios/_TasaCambiosListar.cshtml
@model IEnumerable<Entidades.TasaCambios>

<div class="panel panel-default">
    <div class="panel-heading">
        @ViewBag.Heading
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                @Html.ActionLink("Agregar", "TasaCambiosAdd", "TasaCambios", null, new { @class = "btn btn-primary", data_modal = "" })
            </div>
        </div>
        <table id="grid" class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdMonedaLocal)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IdMonedaExtranjera)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TCoficial)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TCventa)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TCcompra)
                    </th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Monedas.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Monedas1.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TCoficial)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TCventa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TCcompra)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Editar", "TasaCambiosEdit", new { id = item.IdTasaCambio }, new { data_modal = "" })</li>
                                <li>@Html.ActionLink("Eliminar", "TasaCambiosEliminar", new { id = item.IdTasaCambio }, new { data_modal = "" })</li>
                            </ul>
                        </div>
                </tr>
                }
            </tbody>

        </table>

    </div>
</div>

<script src="~/Scripts/app/modalform.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#grid').DataTable({
            "lengthMenu": [[10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"]]
            //"pageLength": 200
        });
    });
</script>